### ISSUE TITLE
Any plans to introduce upserting?

### ISSUE THREAD

**Issue by filipstachura** [mbq/rethinker#1]
Is there any way to insert with upsert enabled? I would like to achieve same as this JS: 
```
r.table('marvel')
 .insert({ superhero: 'Iron Man', superpower: 'Arc Reactor' }, {upsert: true})
 .run()```

**Comment by mbq** [comment]
Basically it is supported, since rethinker forwards everything to RethinkDB as it goes; the syntax for options is just to use named arguments, i.e.:

```r
r()$table("marvel")$
 insert(list(superhero="Iron Man",superpower="Arc Reactor"),upsert=TRUE)$run(con)
````

Still, this is old RethinkDB API; now you probably want to use `insert(...,conflict="update")`.

**Comment by filipstachura** [comment]
Okey, this is cool (and it's answered my question).

As a follow up question (as I think forwarding of args is the key here): How I can forward arguments in this case:

`r.db('test').tableCreate('dc_universe', {primaryKey: 'name'}).run(conn);`

I would go with:

`r()$db("test")$tableCreate("dc_universe", primaryKey = "name")$run(conn)`

but all I get is:

```
Error in fetchResponseRaw(x, token) : 
  Error: Unrecognized optional argument `primaryKey`.
```

**Comment by mbq** [comment]
Internally, rethink uses snake_case rather than camelCase; `primary_key` should do the trick.

**Comment by filipstachura** [comment]
Great! Thanks for your help and quick responses.

Closing.
