### ISSUE TITLE
eqjoin question

### ISSUE THREAD

**Issue by rclations** [mbq/rethinker#2]
I’m running
```test <- r()$db("database")$table("table")$eqJoin(list('secondary_index', r()$db('database')$table('table'), list(index='secondary_index')))$run(cn)```
but getting the error `Error in toJSON(Q$query) : unable to convert R type 4 to JSON

any idea what I'm doing wrong here?

**Comment by mbq** [comment]
The proper syntax would be rather
```r
r()$db("database")$table("table")$eqJoin(
 "secondary_index",
 r()$db("database")$table("table"),
 list(index="secondary_index")
)$run(cn)
```
or, shorter,
```r
r("database","table")$eqJoin(
 "secondary_index",
 r("database","table"),
 list(index="secondary_index")
)$run(cn)
```
However, this does end up in error, `Error: Expected 3 arguments but found 4.`, which suggests that rethinker has serialised the query in a wrong way, so it is certainly a bug. I have to investigate this further. It does work when index option is not used, though.

**Comment by rclations** [comment]
awesome, thanks a ton for the help!
