### ISSUE TITLE
Advanced filtering example

### ISSUE THREAD

**Issue by filipstachura** [mbq/rethinker#4]
Hi Miron,

Could you please add a minimal example of predicate based filtering? 

What is the equivalent to the javascripe below?
```
r.table("users").filter(r.row("age").gt(18)).run(conn, callback)
```

**Comment by mbq** [comment]
`row` is not implemented; but you can use the lambda version, i.e. like JS
```javascript
r.table("users").filter(function(x){return(x("age").gt(18))}).run(conn, callback)
```
For rethinker, `x("...")` must be changed into `x$bracket("...")`, so
```r
r()$table("users")$filter(function(x) x$bracket("age")$gt(18))$run(conn)
```

I'll look into implementing `row`.

**Comment by mbq** [comment]
Ok, I see `row` is just a pretty twisted client-side syntax sugar for a function with one argument; also [the docs](https://rethinkdb.com/docs/writing-drivers/) clearly does not require supporting it.

Thus I won't be adding this, at most as a placeholder to throw a relevant error when used.
