### ISSUE TITLE
Example to insert/update a Date attribute

### ISSUE THREAD

**Issue by fcjbispo** [mbq/rethinker#5]
Hi,

Can you please provide me a code example to build a valid datetime attribute on a table using a class Date variable in R?
I have tried to use the Date field directly but it is creating a integer field rather than a r.ISO8601 format, and i only could get a valid even string format using the format function that is not what i need.

Example:
.q[[.x]]<-list(
        Date = format(bmfaQuotes$Date[.x],'%Y-%m-%dT17:00:00'),
        Open = bmfaQuotes$Open[.x],
        High = bmfaQuotes$High[.x],
        Low = bmfaQuotes$Low[.x],
        Close = bmfaQuotes$Close[.x],
        Volume = bmfaQuotes$Volume[.x],
        Adjusted = bmfaQuotes$Adjusted[.x] 
      )

Thank you so much.

Francisco.

**Comment by mbq** [comment]
Rethink uses its own, non-trivial time format, and one has to use it to allow time-aware queries to work. Hence, it is best to use rethink API functions to convert; consequently, adding a `Date` object using epoch time would look like:

```r
somedate<-Sys.Date()
...$insert(list(
 id='some_object',
 aDate=r()$epochTime(as.numeric(as.POSIXct(somedate)))
))$run(...)
```
You might need to use [`$iso8601`](https://rethinkdb.com/api/javascript/iso8601/) to store timezone information as well, but the idea is the same.

Note that you'll probably need to use `$toIso8601` and `$toEpochTime` to retrieve the dates in a nice form, otherwise you'll get a raw rethink pseudo-object with `reql_type` `epoch_time` and `timezone` elements.

**Comment by fcjbispo** [comment]
Great.

Thank you. It's enough for me.

Regards,

Francisco.

*Francisco C J Bispo*
* *fcjbispo@gmail.com <fbispo.fba@gmail.com>*
 55 11 94969-2144
 55 11 94249-5588
LinkedIn: http://br.linkedin.com/pub/francisco-c-j-bispo/9/a11/315

2017-05-08 11:05 GMT-03:00 Miron Kursa <notifications@github.com>:

**Comment by fcjbispo** [comment]
Hi Miron

I have success using $iso8961 whith simple document, but when i try to do
the same in a more complex document, i got this error:

Error in toJSON(Q$query) : unable to convert R type 4 to JSON

The datetime with timestamp i'm using is this:

> format(bmfaQuotes$Date[.x],'%Y-%m-%dT17:00:00-03:00')
[1] "2007-08-07T17:00:00-03:00"

Can you help me with some others hints to help me?

Thanks.

*Francisco C J Bispo*
* *fcjbispo@gmail.com <fbispo.fba@gmail.com>*
 55 11 94969-2144
 55 11 94249-5588
LinkedIn: http://br.linkedin.com/pub/francisco-c-j-bispo/9/a11/315

2017-05-08 11:34 GMT-03:00 Francisco C J Bispo <fcjbispo@gmail.com>:

**Comment by mbq** [comment]
Can you share an exact query? Seems like a syntax error...

**Comment by fcjbispo** [comment]
Hi,

The complete code with the document building is below. At line 39 i have
the date construction with the code that works and don't marked as comment.

Thank for your time and help.

#--
# loading instruments for each list of type 'BDI'

.f<-list(
  Market = "BM&F BOVESPA",
  Source = "BOVESPA",
  Type = "Stock",
  Code = "BDI"
  )

r(.rDb, "Lists")$filter(.f)$run(rGetConn()) -> .c0

.c<-cursorNext(.c0)
while(!isCursorEmpty(.c0)) {
  print(paste0("Working on List [", .c$Source, ',', .c$Code, ',', .c$Name,
']'))

  for (.j in 1:length(.c$Symbols)){
    .f<-list(
      Market  = .c$Market,
      Source  = .c$Source,
      Symbol  = .c$Symbols[.j],
      Type    = .c$Type
    )

    r(.rDb, "Instruments")$filter(.f)$count()$run(rGetConn()) -> .s

    bmfaDetails<-pgGetDataFrame(
      pgReadQueryFromfile('sql/pgBMFA_Instruments_Details.sql',
list(.c$Symbols[.j]))
    )

    bmfaQuotes<-pgGetDataFrame(
      pgReadQueryFromfile('sql/pgBMFA_Instruments_Quotes.sql',
list(.c$Symbols[.j]))
    )

    .q<-list()
    for (.x in 1:length(bmfaQuotes)) {

      .q[[.x]]<-list(

   #this fails on Error in toJSON(Q$query) : unable to convert R type 4 to
JSON
        #Date =
r()$iso8601(format(bmfaQuotes$Date[.x],'%Y-%m-%dT17:00:00-03:00')),
# this works fine
        Date = format(bmfaQuotes$Date[.x],'%Y-%m-%dT17:00:00-03:00'),
        Open = bmfaQuotes$Open[.x],
        High = bmfaQuotes$High[.x],
        Low = bmfaQuotes$Low[.x],
        Close = bmfaQuotes$Close[.x],
        Volume = bmfaQuotes$Volume[.x],
        Adjusted = bmfaQuotes$Adjusted[.x]
      )
    }

    .d<-list(
      Issuer = bmfaDetails$Issuer,
      "ISIN Code" = bmfaDetails$`ISIN Code`,
      Currency = bmfaDetails$Currency,
      "Currency Symbol" = bmfaDetails$`Currency Symbol`
    )

    .n<-list()
    .n[[1]]<-list(
        Name="CODIGO BDI",
        Value = bmfaDetails$`BDI Code`)
    .n[[2]]<-list(
      Name="BDI",
      Value = bmfaDetails$BDI)
    .n[[3]]<-list(
      Name="CODIGO TIPO MERCADO",
      Value = bmfaDetails$`Market Type Code`)
    .n[[4]]<-list(
      Name="TIPO MERCADO",
      Value = bmfaDetails$`Market Type`)

    .t<-list(
      Market  = .c$Market,
      Source  = .c$Source,
      Symbol  = .c$Symbols[.j],
      Type    = .c$Type,
      Details = .d,
      Specifications = .n,
      Quotes = .q
    )

    if(.writeResults) {
      .fileName<-paste0('./quotes/',.f$Source, '_',
                        .c$Name, '_', .f$Type, '_',
                        .f$Symbol, '.json')
      write(file = .fileName, toJSON(.t))
    }

    if (.s==1) {
      r(.rDb, "Instruments")$filter(.f)$update(.t)$run(rGetConn()) -> .r0
    } else {
      r(.rDb, "Instruments")$insert(.t,
                              conflict="update",
                              return_changes=FALSE)$run(rGetConn()) -> .r0
    }

    print(paste0("Instrument [",.f$Symbol, '] = ',
                 .r0$replaced , ' replaced, ',
                 .r0$inserted, ' inserted, ',
                 .r0$deleted, ' deleted, ',
                 .r0$errors, ' errors'))

  }

  .c<-cursorNext(.c0)
}
close(.c0)
#--

*Francisco C J Bispo*
* *fcjbispo@gmail.com <fbispo.fba@gmail.com>*
 55 11 94969-2144
 55 11 94249-5588
LinkedIn: http://br.linkedin.com/pub/francisco-c-j-bispo/9/a11/315

2017-05-08 20:31 GMT-03:00 Miron Kursa <notifications@github.com>:

**Comment by mbq** [comment]
Well, hard to tell, but I think it will be enough to un-comment `#Date` here:
```r
#Date =
r()$iso8601(format(bmfaQuotes$Date[.x],'%Y-%m-%dT17:00:00-03:00')),
```

Anyway, there probably is a bug in a code mapping nested lists into arrays and objects; I will investigate this further.

**Comment by mbq** [comment]
Have this fixed the problem? There were some other bugs which might influence this, which are still in the CRAN version; in case your problem persists, please try the devel-branch version from GitHub.

**Comment by fcjbispo** [comment]
Hi Miron,

Yeah, i'm still facing that issue and using a string date for while.. Now
i'm having troubles with replace/update functions with some documents with
unicode (ã,ç,á, ê...) letters inside.

To use the devel branch i have to clone, build and manually install the
package? I don't know how to do it...

Thanks a lot.

*Francisco C J Bispo*
* *fcjbispo@gmail.com <fbispo.fba@gmail.com>*
 55 11 94969-2144
 55 11 94249-5588
LinkedIn: http://br.linkedin.com/pub/francisco-c-j-bispo/9/a11/315

2017-05-17 12:21 GMT-03:00 Miron Kursa <notifications@github.com>:

**Comment by mbq** [comment]
The easiest way is to install the devtools package and then:

```R
devtools::install_github("mbq/rethinker",ref='devel')
```

For your Unicode problem, can you make another issue (as it is unrelated to the date thing)? I'm pretty surprised that it happens, rjson should escape it correctly...

**Comment by fcjbispo** [comment]
Thanks for the clue about install dev package.

In fact, i`m not sure if the new issue its related with unicode, once i had
another table with documents that has unicode characters in it...

When i will be sure what is happening i will open a new issue.

Thanks a lot.

*Francisco C J Bispo*
* *fcjbispo@gmail.com <fbispo.fba@gmail.com>*
 55 11 94969-2144
 55 11 94249-5588
LinkedIn: http://br.linkedin.com/pub/francisco-c-j-bispo/9/a11/315

2017-05-17 19:23 GMT-03:00 Miron Kursa <notifications@github.com>:

**Comment by fcjbispo** [comment]
Hello,

I realized out that i had to submit the
r()$iso8601(format(bmfaQuotes$Date[.x],'%Y-%m-%dT17:00:00-03:00')) call to
a running connection in order to fully build a valid date object prior to
send the document to the database.

So, i changed my function to send the r()$iso8601() call to the server,
build the date object and then attached it on the final document and send
it again.

Now it`s working. You can close this issue.

Thank you for the support.

*Francisco C J Bispo*
* *fcjbispo@gmail.com <fbispo.fba@gmail.com>*
 55 11 94969-2144
 55 11 94249-5588
LinkedIn: http://br.linkedin.com/pub/francisco-c-j-bispo/9/a11/315

2017-05-17 19:23 GMT-03:00 Miron Kursa <notifications@github.com>:

**Comment by mbq** [comment]
Ok, thanks.
