### ISSUE TITLE
Obtaining changes delta without closing the connection.

### ISSUE THREAD

**Issue by filipstachura** [mbq/rethinker#9]
Hi Miron,

thank you for your work on this package! 💯 🎉 

We are trying to take advantage of asynchronous queries in our project (https://github.com/Appsilon/shiny.collections).

Draining connection to receive updates is not an option for us as we need to keep connection alive. We've been thinking about adding `checkConnection` function to rethinker:
```
checkConnection<-function(x){
  if (length(x$handlers) > 0) {
    if (rethinker::isOpened(x)) {
      fetchResponseRaw(x)
    }
  }
}
```

We are aware that `fetchResponseRaw` needs some changes as well. It should try to read from a socket and return within a given timeout (and perhaps if timeout == NULL, immediately). 

We were successful in receiving changes, but currently code is blocking (as `readBin` is blocking). We have tried to use [socketSelect](https://www.rdocumentation.org/packages/base/versions/3.4.1/topics/socketSelect) but this one returns FALSE even if there are changes being send. Additionally, there is no way to specify timeout for `readBin`. Do you have any ideas how to make it work?

Thanks,
Filip

**Comment by filipstachura** [comment]
@mbq - just adding mention, in case you didn't see it previously

**Comment by mbq** [comment]
Thanks for mention, I've messed up my notification settings.

Anyway, back to the topic. This could be done by using async socket in rethinker, but this is a pain to use in R... Quite likely I should re-write rethinker to have wire.R implemented in C and running in a thread, only eating and emitting complete events (which would also enable TLS), but this is a substantial effort.

For the time being, I can only think of spawning separate processes for rethinker, calling drainConnection there and making async pipe between process to exchange commands and events.

**Comment by filipstachura** [comment]
The problems I see with spawning separate processes is managing deltas.
1. If we (stop first rethinker process -> send delta through pipe -> start second rethinker process) than we can miss changes being made between stopping and starting rethinker.
2. If we start second process before stopping first one we can receive same changes twice for each process.

If we need to start separate process and managing that through pipes than we can use native JavaScript drivers without the need to close connection in meantime.

**Comment by mbq** [comment]
But why do you want to close connections? When in the drainConnection loop, rethinker is perfectly able to handle many changefeed updates, as well as making new queries.

Using nodejs is also a good idea.

**Comment by filipstachura** [comment]
> When in the drainConnection loop, rethinker is perfectly able to handle many changefeed updates, as well as making new queries.

Got it, thanks. We are going to think about our options and let you know for the reference.

All the best in 2018! 👍
